"""initial schema

Revision ID: e1b4cdee1b60
Revises: 
Create Date: 2026-04-29 21:15:09.623361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b4cdee1b60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('genealogies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('genealogies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genealogies_owner_id'), ['owner_id'], unique=False)

    op.create_table('genealogy_collaborators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genealogy_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='editor', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role in ('viewer', 'editor')", name='ck_collaborator_role'),
    sa.ForeignKeyConstraint(['genealogy_id'], ['genealogies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('genealogy_id', 'user_id', name='uq_genealogy_collaborator')
    )
    with op.batch_alter_table('genealogy_collaborators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genealogy_collaborators_genealogy_id'), ['genealogy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_genealogy_collaborators_user_id'), ['user_id'], unique=False)

    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genealogy_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('death_year', sa.Integer(), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('generation_no', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("gender in ('male', 'female', 'unknown')", name='ck_member_gender'),
    sa.CheckConstraint('death_year is null or birth_year is null or death_year >= birth_year', name='ck_member_life_years'),
    sa.CheckConstraint('generation_no >= 1', name='ck_member_generation'),
    sa.ForeignKeyConstraint(['genealogy_id'], ['genealogies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_members_genealogy_id'), ['genealogy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_name'), ['name'], unique=False)
        batch_op.create_index('ix_members_name_trgm', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})

    op.create_table('marriages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genealogy_id', sa.Integer(), nullable=False),
    sa.Column('spouse1_member_id', sa.Integer(), nullable=False),
    sa.Column('spouse2_member_id', sa.Integer(), nullable=False),
    sa.Column('married_year', sa.Integer(), nullable=True),
    sa.Column('ended_year', sa.Integer(), nullable=True),
    sa.CheckConstraint('ended_year is null or married_year is null or ended_year >= married_year', name='ck_marriage_years'),
    sa.CheckConstraint('spouse1_member_id < spouse2_member_id', name='ck_marriage_ordered_pair'),
    sa.ForeignKeyConstraint(['genealogy_id'], ['genealogies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spouse1_member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spouse2_member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spouse1_member_id', 'spouse2_member_id', name='uq_marriage_pair')
    )
    with op.batch_alter_table('marriages', schema=None) as batch_op:
        batch_op.create_index('ix_marriages_genealogy_spouse1', ['genealogy_id', 'spouse1_member_id'], unique=False)
        batch_op.create_index('ix_marriages_genealogy_spouse2', ['genealogy_id', 'spouse2_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marriages_genealogy_id'), ['genealogy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marriages_spouse1_member_id'), ['spouse1_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marriages_spouse2_member_id'), ['spouse2_member_id'], unique=False)

    op.create_table('parent_child_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genealogy_id', sa.Integer(), nullable=False),
    sa.Column('parent_member_id', sa.Integer(), nullable=False),
    sa.Column('child_member_id', sa.Integer(), nullable=False),
    sa.Column('parent_role', sa.String(length=10), nullable=False),
    sa.CheckConstraint("parent_role in ('father', 'mother')", name='ck_parent_role'),
    sa.CheckConstraint('parent_member_id <> child_member_id', name='ck_parent_not_child'),
    sa.ForeignKeyConstraint(['child_member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genealogy_id'], ['genealogies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_member_id', 'child_member_id', name='uq_parent_child')
    )
    with op.batch_alter_table('parent_child_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parent_child_relations_child_member_id'), ['child_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_child_relations_genealogy_id'), ['genealogy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_child_relations_parent_member_id'), ['parent_member_id'], unique=False)
        batch_op.create_index('ix_parent_child_genealogy_child', ['genealogy_id', 'child_member_id'], unique=False)
        batch_op.create_index('ix_parent_child_genealogy_parent', ['genealogy_id', 'parent_member_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_child_relations', schema=None) as batch_op:
        batch_op.drop_index('ix_parent_child_genealogy_parent')
        batch_op.drop_index('ix_parent_child_genealogy_child')
        batch_op.drop_index(batch_op.f('ix_parent_child_relations_parent_member_id'))
        batch_op.drop_index(batch_op.f('ix_parent_child_relations_genealogy_id'))
        batch_op.drop_index(batch_op.f('ix_parent_child_relations_child_member_id'))

    op.drop_table('parent_child_relations')
    with op.batch_alter_table('marriages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marriages_spouse2_member_id'))
        batch_op.drop_index(batch_op.f('ix_marriages_spouse1_member_id'))
        batch_op.drop_index(batch_op.f('ix_marriages_genealogy_id'))
        batch_op.drop_index('ix_marriages_genealogy_spouse2')
        batch_op.drop_index('ix_marriages_genealogy_spouse1')

    op.drop_table('marriages')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index('ix_members_name_trgm')
        batch_op.drop_index(batch_op.f('ix_members_name'))
        batch_op.drop_index(batch_op.f('ix_members_genealogy_id'))

    op.drop_table('members')
    with op.batch_alter_table('genealogy_collaborators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genealogy_collaborators_user_id'))
        batch_op.drop_index(batch_op.f('ix_genealogy_collaborators_genealogy_id'))

    op.drop_table('genealogy_collaborators')
    with op.batch_alter_table('genealogies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genealogies_owner_id'))

    op.drop_table('genealogies')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
