"""add relation constraints and indexes

Revision ID: eb4cc1a0641e
Revises: e1b4cdee1b60
Create Date: 2026-04-29 21:26:31.163496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb4cc1a0641e'
down_revision = 'e1b4cdee1b60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_child_relations', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_child_parent_role', ['child_member_id', 'parent_role'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_child_relations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_child_parent_role', type_='unique')

    # ### end Alembic commands ###
